apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
data:
  traefik.yml: |
    api:
      dashboard: true
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    certificatesResolvers:
      default:
        acme:
          email: david.makosso@etna-alternance.net
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
